### PR TITLE
VPS-007/Add labels in toolbar

### PR DESCRIPTION
**Pull request by lia-arroyo**
---
title: "[VPS-007] Add labels in toolbar"
---

## Describe the issue

Based on the user story: "As a user I'd like to clearly interpret what each tool in the toolbar is"

## Describe the solution

Added labels next to the icons in the scene editing toolbar.

## Risk

Minimal to none

## DoD

- [ ] Code peer-reviewed
- [ ] Wiki Documentation is written and up to date
- [ ] Unit tests written and passing
- [ ] Integration tests written and passing
- [ ] Continuous Integration build passing
- [ ] Acceptance criteria met
- [ ] Deployed to production environment

## Reviewed By

Who reviewed your PR - for commit history once merged

### CODE REVIEW

**Comment by nickykay98** [comment]
So quick, great stuff! Can you please:

1. See if you can pass the 2 failing checks (they look like code style checks)?
2. Match the branch number (007) with the PR number (559) by just editing the PR number in the title and description above?
2. Let me know where you got the pull request template above? Can't seem to find it in the repo, would be great to have other team members use it too!

**Comment by lia-arroyo** [comment]
1. I'll look into the failed tests now 😄 

2. The branch number and PR numbers weren't auto-generated, and I wasn't sure which numbers to use so I just used the ticket number (007) for the branch and the (latest commit number + 1) for the commit. 
I've changed the PR number to match now. 

For the future though, which one should I use? 

3. The PR template was automatically generated when I clicked on 'Compare and Pull Request'. 

Thanks!

**Comment by nickykay98** [comment]
1. Thanks! Shouldn't be a problem if you can't pass that last test, can always discuss them at the next meeting (wasn't aware there were tests for frontend in the first place haha)
2.  Whatever number you want, but keep them the same for your story (aka issue), its PR, and all commits in that PR - don't worry, I will add to the conventions already in the README to explicitly state this for everyone!
3. Ooh that's handy, noted, thanks!

**Comment by lia-arroyo** [comment]
1. Yep, that is my understanding as well. Here is the resource I was reading: https://jestjs.io/docs/snapshot-testing. I'm currently busy with uni at the moment so I likely wouldn't be able to work on it until next week, so feel free to merge and close when you're ready :) 
2. Noted, thanks!

**Comment by nickykay98** [comment]
Potential future work (from Lia on Slack): I think we need to update the snapshots through the CLI

**Pull request merged**
