### PR TITLE
VPS-53/Image Upload Issue

### PR DESCRIPTION
**Pull request by codecreator127**
AuthoringToolPage

## Describe the issue

Images do not get saved correctly when saving quickly and leaving

## Describe the solution

Added await to the savescene() 

image

## Risk

Might break images

## Definition of Done

- [ ] Code peer-reviewed
- [ ] Wiki Documentation is written and up to date
- [ ] Unit tests written and passing
- [ ] Integration tests written and passing
- [ ] Continuous Integration build passing
- [ ] Acceptance criteria met
- [ ] Deployed to production environment

## Reviewed By

Who reviewed your PR - for commit history once merged

### CODE REVIEW

**Review by JordanBlenn — APPROVED** [review]
:)

**Review by wjin-lee — APPROVED** [review]
nice! good spotting

**Comment by codecreator127** [comment]
> nice! good spotting

thank you !

**Comment by Kot6603** [comment]
> nice! good spotting

it was the most difficult bug to find

**Pull request merged**
