### PR TITLE
Vps 032/implement prototype dashboard

### PR DESCRIPTION
**Pull request by mlai962**
## Describe the issue

Implement the prototype dashboard created in Figma in the last sprint into the app (just the frontend, other people are working on the backend logic)

## Describe the solution

Implemented the dashboard with a scene graph and node tooltips.

## Risk

Unauthorised access to dashboard page.

## Definition of Done

- [ ] Code peer-reviewed
- [ ] Wiki Documentation is written and up to date
- [ ] Unit tests written and passing
- [ ] Integration tests written and passing
- [ ] Continuous Integration build passing
- [ ] Acceptance criteria met
- [ ] Deployed to production environment

## Reviewed By

Who reviewed your PR - for commit history once merged

### CODE REVIEW

**Comment by nickykay98** [comment]
@mlai962 Please resolve the conflicts above 😊

**Comment by mlai962** [comment]
After fixing merge conflicts the app runs but tests aren't passing. A few of the tests are to do with the node version we have and compatibility with a graphing dependency, I'm not sure how to solve these.

**Comment by nickykay98** [comment]
@mlai962 Did you manage to fix the unit tests? If not, @mlai962 @DamonGreenhalgh please help if you can, would like to wrap things up by this coming Wednesday :)

**Comment by mlai962** [comment]
I haven’t been working on it, the test failing is to do with it expecting a node version >= 14, our project is on 12.x, but the app still runs.

**Comment by nickykay98** [comment]
Ok I'll just merge it

**Pull request merged**
