### PR TITLE
VPS-022/Timer

### PR DESCRIPTION
**Pull request by lia-arroyo**
## Describe the issue

To be able to add a time constant to the scene. After the timer ends, the scene can either end or prompt for restart. Based on Issue #22

## Describe the solution

MVP for this story is being able to add a timer for each scene, allowing the editor to customise how much time a user can spend on any given scene. At the end of the timer there will be a prompt (either pop-up stopping the scenario or prompting for a restart).

## Risk

Low risk

#### Some issues/concerns to take care of next time:
- **There isn't a clear way for users to indicate that they don't need a timer for the scene.** At the moment, setting it to 0 and not entering a value does this, but this could cause confusion in the future. Matthew suggested potentially adding a 'no time limit checkbox'. 
-  **Material UI Shrink label overlap.** Since the shrink is managed manually, adding any '-' or '+' symbols (which is allowed in the number field) causes the overlap to occur, so need to remove this ability. 
Also, the label doesn't move when clicked, unless you enter a value (which is inconsistent with the 'Scene Name' field shrink animation). 

## Definition of Done

- [ ] Code peer-reviewed
- [ ] Wiki Documentation is written and up to date
- [ ] Unit tests written and passing
- [ ] Integration tests written and passing
- [ ] Continuous Integration build passing
- [ ] Acceptance criteria met
- [ ] Deployed to production environment

### CODE REVIEW

**Comment by lia-arroyo** [comment]
Hi team,

Sorry for the email spam (hopefully you guys haven't been receiving them :')) but I managed to pass 5 out of the 6 test cases. 

I'm not sure how to fix the failing backend unit tests, could someone else please have a look at them? Maybe @aadenmann or @jfen445 since you guys worked on the backend? 

Thanks :)

**Comment by nickykay98** [comment]
@aadenmann @jfen445 Have a look at the failing backend test if you can, otherwise I'll merge tomorrow

**Comment by aadenmann** [comment]
I issue was that when duplicating the scenes, it wasnt copying the value of timer over to the new copy, instead it was undefined, I havent found a fix for that yet but for the test case to pass ive just removed that line of code for now. ill try and fix it now.

**Comment by aadenmann** [comment]
Fixed scene duplicate feature, now works and test all pass

**Pull request merged**
