### PR TITLE
Vps 073/null name bug

### PR DESCRIPTION
**Pull request by John-Moore-UOA**
## Describe the issue

When user changes scene or scenario name, if they leave the name-space as blank, the back end crashes.

## Describe the solution

Create a temp variable to hold the name, then change the name and if the new name is empty or blank, revert to the temp variable.

## Risk

A mistake could carry through and bug other aspects of the backend

## Definition of Done

- [ ] Code peer-reviewed
- [ ] Wiki Documentation is written and up to date
- [ ] Unit tests written and passing
- [ ] Integration tests written and passing
- [ ] Continuous Integration build passing
- [ ] Acceptance criteria met
- [ ] Deployed to production environment

## Reviewed By

Who reviewed your PR - for commit history once merged

### CODE REVIEW

**Comment by John-Moore-UOA** [comment]
The patch I have submitted does not update the name-space in real time.  It only fixes itself on a reload of the page.

**Comment by arnard76** [comment]
Moved this PR to draft until we can prevent empty name input in the UI (by reverting to previous name + showing message indicating the empty name issue)

**Comment by John-Moore-UOA** [comment]
This is what I would like to consider finished, but there is a bug found once, and I cannot reproduce. 

It was "Unhandled Rejection (TypeError): Cannot read properties of null (reading '_id')" 
It ocured when I tried to inspect the list-container Name element of a scene.

**Comment by John-Moore-UOA** [comment]
Could you explain what this means:
"...showing message indicating the empty name issue)"

Thanks

**Comment by arnard76** [comment]
Yea sure,
If the user tries to make the name empty and the app reverts it back to previous non-empty name, then users can understand why that happened by reading a message that pops up below the name input.

**Comment by John-Moore-UOA** [comment]
> Yea sure, If the user tries to make the name empty and the app reverts it back to previous non-empty name, then users can understand why that happened by reading a message that pops up below the name input.

This has now been implemented.  

The style is now the key aspect of this problem.

**Review by djos192 — APPROVED** [review]

**Pull request merged**
